#' Define Pilot Systems for Simulation
#'
#' This function defines a list of systems for generating simulated data.
#'
#' \strong{System 1:} Modified Non-linear System with External Actions,
#' using environment parameters:
#'   \code{mu_A1, sigma_A1} (for external action in X1) and
#'   \code{mu_A2, sigma_A2} (for external action in X5).
#'
#' \strong{System 2:} A 7-variable "medium" system, in which
#'   \eqn{X_1,\dots,X_7} plus \eqn{Z} are generated by:
#'   \itemize{
#'     \item \eqn{X_1 = \varepsilon_1}
#'     \item \eqn{X_2 = X_1 + \varepsilon_2}
#'     \item \eqn{X_3 = X_1 + X_2 + \varepsilon_3}
#'     \item \eqn{Z  = \sin(5 \,X_2) + (X_3)^3 + \varepsilon_Z}
#'     \item \eqn{X_4 = X_2 + \varepsilon_4}
#'     \item \eqn{X_5 = Z + \varepsilon_5} (we treat \eqn{X_5} as Y)
#'     \item \eqn{X_6 = Z + \varepsilon_6}
#'     \item \eqn{X_7 = X_6 + \varepsilon_7}
#'   }
#'   If you call \code{data_func(n, environment = list(sd_eps=...))}, it uses
#'   \code{sd_eps} as the noise scale.
#'
#' @return A list of systems. Each system is a list containing:
#'   \item{name}{Name of the system.}
#'   \item{description}{A description of the system's structural equations.}
#'   \item{data_func}{A function to generate data for the system.}
#'
#' @export
#'
#' @examples
#' systems <- pilot_systems()
#' # Generate data from the first system
#' data1 <- systems[[1]]$data_func(n = 1000)
#' # Generate data from the second system (7-variable medium system):
#' data2 <- systems[[2]]$data_func(n = 1000, environment = list(sd_eps=2))
#'
pilot_systems <- function() {
  systems <- list(
    
    # System 1: Modified Non-linear System with External Actions
    list(
      name = "Modified Non-linear System with External Actions",
      description = paste(
        "Equations:",
        "X1 = epsilon1 + A1;",
        "Y = sin(X1) + epsilonY;",
        "X2 = Y^2 + A2 + epsilon2."
      ),
      data_func = function(n, environment = list(mu_A1=0, sigma_A1=1, mu_A2=0, sigma_A2=1)) {
        epsilon1 <- rnorm(n)
        epsilonY <- rnorm(n)
        epsilon2 <- rnorm(n)
        
        A1 <- rnorm(n, mean = environment$mu_A1, sd = environment$sigma_A1)
        A2 <- rnorm(n, mean = environment$mu_A2, sd = environment$sigma_A2)
        
        X1 <- epsilon1 + A1
        Y  <- sin(X1) + epsilonY
        X2 <- Y^2 + A2 + epsilon2
        
        data <- data.frame(X1, X2, Y)
        return(data)
      }
    ),
    
    # System 2: 7-variable "medium" system
    list(
      name = "7-Variable Medium System",
      description = paste(
        "X1 = eps1",
        "X2 = X1 + eps2",
        "X3 = X1 + X2 + eps3",
        "Z  = sin(5 * X2) + (X3)^3 + epsZ",
        "X4 = X2 + eps4",
        "X5 = Z + eps5  (treated as Y)",
        "X6 = Z + eps6",
        "X7 = X6 + eps7"
      ),
      data_func = function(n, environment = list(sd_eps=1)) {
        # environment$sd_eps controls the standard deviation of noise
        sd_eps <- environment$sd_eps
        
        eps1 <- rnorm(n, 0, sd_eps)
        eps2 <- rnorm(n, 0, sd_eps)
        eps3 <- rnorm(n, 0, sd_eps)
        epsZ <- rnorm(n, 0, sd_eps)
        eps4 <- rnorm(n, 0, sd_eps)
        eps5 <- rnorm(n, 0, sd_eps)
        eps6 <- rnorm(n, 0, sd_eps)
        eps7 <- rnorm(n, 0, sd_eps)
        
        X1 <- eps1
        X2 <- X1 + eps2
        X3 <- X1 + X2 + eps3
        Z  <- sin(5 * X2) + (X3)^3 + epsZ
        X4 <- X2 + eps4
        X5 <- Z + eps5  # Y
        X6 <- Z + eps6
        X7 <- X6 + eps7
        
        df <- data.frame(X1, X2, X3, X4, X5, X6, X7, Z)
        # rename X5 -> Y for clarity if you want, or keep X5 as is
        df$Y <- df$X5
        return(df)
      }
    )
  )
  return(systems)
}
